
CREATE TABLE AFILIADO (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(20),
    FOLLOWERS INT,
    COUPON VARCHAR(50),
    DISCOUNT DECIMAL(3,2)
);

CREATE TABLE FEEDBACK (
    ID INT PRIMARY KEY,
    PRODUCT_ID INT,
    RATING INT,
    COMMENT TEXT,
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);

CREATE TABLE PRODUCT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    PRICE DECIMAL(10,2),
    IMAGEM VARCHAR(255)
);

CREATE TABLE USERS (
    ID INT PRIMARY KEY,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255)
);

